const KEY="spendly_expenses_v1",THEME="spendly_theme_v1";let expenses=load(),filter="all";
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const money=n=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",minimumFractionDigits:2}).format(n);
const fmtDate=s=>new Intl.DateTimeFormat("en-NG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(s+"T00:00:00"));
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(expenses))}
function render(){summary();filters();list();breakdown()}
function summary(){let total=expenses.reduce((a,e)=>a+e.amount,0),month=expenses.filter(e=>e.date.slice(0,7)===today().slice(0,7)).reduce((a,e)=>a+e.amount,0);$("total").textContent=money(total);$("month").textContent=money(month);$("average").textContent=money(expenses.length?total/expenses.length:0);$("count").textContent=`${expenses.length} ${expenses.length===1?"expense":"expenses"}`;$("monthName").textContent=new Intl.DateTimeFormat("en-NG",{month:"long",year:"numeric"}).format(new Date())}
function filters(){let cats=[...new Set(expenses.map(e=>e.category))].sort();$("filter").innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join("");$("filter").value=cats.includes(filter)||filter==="all"?filter:"all";filter=$("filter").value}
function list(){let data=[...expenses].filter(e=>filter==="all"||e.category===filter).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);$("list").innerHTML="";$("empty").style.display=data.length?"none":"block";data.forEach(e=>{let row=document.createElement("article");row.className="expense";row.innerHTML=`<div class="cat">${(e.category[0]||"O").toUpperCase()}</div><div><p class="desc">${esc(e.description)}</p><p class="meta">${esc(e.category)} · ${fmtDate(e.date)}</p></div><div class="amount">${money(e.amount)}</div><button class="delete" aria-label="Delete expense">×</button>`;row.querySelector(".delete").onclick=()=>del(e.id);$("list").appendChild(row)})}
function breakdown(){let totals={};expenses.forEach(e=>totals[e.category]=(totals[e.category]||0)+e.amount);let data=Object.entries(totals).sort((a,b)=>b[1]-a[1]),sum=data.reduce((a,[,v])=>a+v,0);$("breakdown").innerHTML=data.length?data.map(([c,v])=>`<div class="break"><div class="break-top"><span>${esc(c)}</span><span>${money(v)}</span></div><div class="bar"><span style="width:${sum?v/sum*100:0}%"></span></div></div>`).join():'<p class="sub">Your category breakdown will appear here after you add an expense.</p>'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function open(){ $("backdrop").hidden=false;document.body.style.overflow="hidden";$("date").value=today();setTimeout(()=>$("amount").focus(),30)}
function close(){ $("backdrop").hidden=true;document.body.style.overflow="";$("form").reset();clearErrors()}
function clearErrors(){["amountErr","dateErr","categoryErr","descriptionErr"].forEach(id=>$(id).textContent="")}
function validate(){clearErrors();let ok=true,a=Number($("amount").value),d=$("date").value,c=$("category").value.trim(),desc=$("description").value.trim();if(!Number.isFinite(a)||a<=0){$("amountErr").textContent="Enter an amount greater than ₦0.";ok=false}if(!c){$("categoryErr").textContent="Choose a category.";ok=false}if(!desc){$("descriptionErr").textContent="Add a description.";ok=false}if(!d){$("dateErr").textContent="Choose a date.";ok=false}else if(d>today()){$("dateErr").textContent="Date cannot be in the future.";ok=false}return ok}
$("form").onsubmit=e=>{e.preventDefault();if(!validate())return;expenses.push({id:expenses.length?Math.max(...expenses.map(x=>x.id))+1:1,amount:Math.round(Number($("amount").value)*100)/100,category:$("category").value.trim(),description:$("description").value.trim(),date:$("date").value});save();render();close();toast("Expense added successfully.")}
function del(id){let e=expenses.find(x=>x.id===id);if(!e)return;if(confirm(`Delete "${e.description}" (${money(e.amount)})?`)){expenses=expenses.filter(x=>x.id!==id);save();render();toast("Expense deleted.")}}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),2400)}
$("addTop").onclick=open;$("addEmpty").onclick=open;$("close").onclick=close;$("cancel").onclick=close;$("filter").onchange=e=>{filter=e.target.value;list()};$("backdrop").onclick=e=>{if(e.target===$("backdrop"))close()};document.onkeydown=e=>{if(e.key==="Escape"&&!$("backdrop").hidden)close()};
$("theme").onclick=()=>{document.body.classList.toggle("dark");let d=document.body.classList.contains("dark");localStorage.setItem(THEME,d?"dark":"light");$("theme").textContent=d?"☀":"☾"};
if(localStorage.getItem(THEME)==="dark"){document.body.classList.add("dark");$("theme").textContent="☀"}
$("today").textContent=new Intl.DateTimeFormat("en-NG",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());render();